# Generated by Django 5.0.2 on 2024-03-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('dis_price', models.IntegerField()),
                ('categary', models.CharField(choices=[('phone', 'Phone'), ('book', 'Book')], default='book', max_length=30)),
                ('desc', models.TextField()),
            ],
        ),
    ]
